version: "3.8"
services:
  emitter:
    build:
      context: ./EMITTER
    env_file: ./EMITTER/.env
    command: npm run start-prod
    depends_on:
      - listener
    volumes:
      - .:/LISTENER/

  listener:
    build:
      context: ./LISTENER
    env_file: ./LISTENER/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/LISTENER/
